Disable r10k check

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -108,18 +108,18 @@ else
     echo "rspec not installed. Skipping rspec-puppet tests..."
 fi
 
-#r10k puppetfile syntax check
-if which r10k >/dev/null 2>&1; then
-  if [ $changedfile = "Puppetfile" ]; then
-        ${subhook_root}/r10k_syntax_check.sh
-        RC=$?
-        if [ "$RC" -ne 0 ]; then
-                failures=`expr $failures + 1`
-        fi
-  fi
-else
-    echo "r10k not installed. Skipping r10k Puppetfile test..."
-fi
+# #r10k puppetfile syntax check
+# if which r10k >/dev/null 2>&1; then
+#   if [ $changedfile = "Puppetfile" ]; then
+#         ${subhook_root}/r10k_syntax_check.sh
+#         RC=$?
+#         if [ "$RC" -ne 0 ]; then
+#                 failures=`expr $failures + 1`
+#         fi
+#   fi
+# else
+#     echo "r10k not installed. Skipping r10k Puppetfile test..."
+# fi
 
 #summary
 if [ "$failures" -ne 0 ]; then
